### Load in NumPy (remember to pip install numpy first)

In [101]:
import numpy as np

### The Basics

In [102]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [103]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [104]:
# Get Dimension
a.ndim

1

In [105]:
# Get Shape
b.shape

(2, 3)

In [106]:
# Get Type
a.dtype

dtype('int32')

In [107]:
# Get Size
a.itemsize

4

In [108]:
# Get total size
a.nbytes

12

In [109]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [110]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [111]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [112]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [113]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [114]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [115]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [116]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [117]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [118]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [119]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [120]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [121]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [122]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [123]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [124]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.70276211, 0.4635711 ],
       [0.24912835, 0.06886847],
       [0.92108491, 0.33591946],
       [0.91673791, 0.50915605]])

In [125]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 7, -4,  5],
       [-4,  4,  2],
       [ 0,  3, -2]])

In [126]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [127]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [128]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [129]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [130]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [131]:
a + 2

array([3, 4, 5, 6])

In [132]:
a - 2

array([-1,  0,  1,  2])

In [133]:
a * 2

array([2, 4, 6, 8])

In [134]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [135]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [136]:
a ** 2

array([ 1,  4,  9, 16])

In [137]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [138]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [139]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [140]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [141]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [142]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
np.min(stats)

np.int64(1)

In [144]:
np.max(stats, axis=1)

array([3, 6])

In [145]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [146]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [147]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))